### ISSUE TITLE
Przyciski filtrów są źle zaznaczane

### ISSUE THREAD

**Issue by ghost** [sAleksander/photoBook#8]
Obecnie wszystkie przyciski filtrów (radio buttony) należą do jednej grupy, przez co wybranie filtru dla jednego zdjęcia poprzez wciśnięcie przycisku powoduje odznaczenie się wyboru filtru dla innych zdjęć. Problem jest wyłącznie z UI, samo wybieranie filtrów i ich ustawianie działa prawidłowo.

**Comment by Wojciech-Pisarski** [comment]
Każde zdjęcie zostaje teraz przypisane do osobnej grupy na podstawie jego nazwy (utworzyłem osobny properties w viewModelu zwracający tą nazwę, do którego dodałem binding z view).
Problem jest rozwiązany.
