### ISSUE TITLE
Zarządzanie edytowanymi zdjęciami w folderze

### ISSUE THREAD

**Issue by ghost** [sAleksander/photoBook#9]
Obecnie, w momencie kiedy zdjęcie jest przycinane lub ustawiany jest filtr, obrobione zdjęcie trafia to odpowiedniego folderu i dzieje się tak **za każdym razem**, gdy wykonywane jest przycinanie lub filtrowanie. W ten sposób folder z przerobionymi zdjęciami szybko zapycha się duplikatami lub starymi, niepotrzebnymi zdjęciami. Obecny system trzeba by ulepszyć o co najmniej dwie rzeczy:

- Śledzenie, które przerobione zdjęcia wywodzą się od którego oryginalnego zdjęcia. W ten sposób, usuwając oryginalne zdjęcie (np. ładując w jego miejsce nowe), będziemy mogli usunąć jego wszystkie przerobione wersje.
- Śledzenie, które filtry już zostały nałożone i jeśli filtr ma być nałożony ponownie, to nie tworzyć nowego zdjęcia, a wykorzystać już przerobione.

**Comment by Wojciech-Pisarski** [comment]
Z tym problemem jest kilka mankamentów. Próbowałem usuwać stare zdjęcia (te króre wyświetlane byłby przed zmianą) w modelu na bierząco, po zmianie plików, lecz wynikały z tego problemy z związane z wykorzystywaniem ich jeszcze przez widok.

Później próbowałem zająć się tym podejściem z poziomu widoku i zaraz po chwili podmiany tam starego zdjęcia na nowe wywoływać metodę usuwającą stare zdjęcie, lecz to również skutkowało tym samym błędem co wyżej.

W ostatniej próbie podszedłem do problemu trochę inaczej. W chwili zapisywania foto książki iterowałem przez wszystkie strony naszej fotoksiążki tworzyłem listę zdjęć, które są tam wykorzystywane. Następnie przechodziłem do folderu "EditedImages", z którego chcemy usuwać niepotrzebne zdjęcia i na podstawie sprawdzenia, czy kolejne pliki nie znajdują się na liście wykorzystywanych zdjęć kolejno je kasowałem. Niestety rozwiązanie to nie było do końca dobre. W wielu przypadkach wszystko działało zgodnie z oczekiwaniami, lecz jak się później okazało, zdarzały się również przypadki, w których otrzymywałem ten sam błąd co w wyżej opisanych podejściach.

Wydaje mi się więc, że nic więcej nie jestem w stanie z tym zrobić.
